// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nr5rpcEprooErlzG7yPX7-udTAE5F7s',
    appId: '1:470996064382:web:771dbef4329a59d7d4a02f',
    messagingSenderId: '470996064382',
    projectId: 'recipeapp-4058e',
    authDomain: 'recipeapp-4058e.firebaseapp.com',
    storageBucket: 'recipeapp-4058e.firebasestorage.app',
    measurementId: 'G-0K158Z9P0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofkM1b1k7x-LOCsd5DQRYIOpKGYYVPso',
    appId: '1:470996064382:android:2adcf1075ffabee0d4a02f',
    messagingSenderId: '470996064382',
    projectId: 'recipeapp-4058e',
    storageBucket: 'recipeapp-4058e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSNkCofGOZvwK-w4gkapOYMoQZLK_387o',
    appId: '1:470996064382:ios:c15b66764876c280d4a02f',
    messagingSenderId: '470996064382',
    projectId: 'recipeapp-4058e',
    storageBucket: 'recipeapp-4058e.firebasestorage.app',
    iosBundleId: 'com.example.recipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSNkCofGOZvwK-w4gkapOYMoQZLK_387o',
    appId: '1:470996064382:ios:c15b66764876c280d4a02f',
    messagingSenderId: '470996064382',
    projectId: 'recipeapp-4058e',
    storageBucket: 'recipeapp-4058e.firebasestorage.app',
    iosBundleId: 'com.example.recipeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9nr5rpcEprooErlzG7yPX7-udTAE5F7s',
    appId: '1:470996064382:web:db224553a45ace42d4a02f',
    messagingSenderId: '470996064382',
    projectId: 'recipeapp-4058e',
    authDomain: 'recipeapp-4058e.firebaseapp.com',
    storageBucket: 'recipeapp-4058e.firebasestorage.app',
    measurementId: 'G-7JY8GPDKMN',
  );
}
